name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск ежедневно в полночь по UTC
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GHT }}

          # --- Конфигурация плагинов ---

          # Пример
          # base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

          # Заготовки:
          # plugin_isocalendar: yes
          # plugin_lines: yes
          # plugin_traffic: yes

          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          committer_message: "chore: update GitHub metrics"

          # --- Дополнительные опции ---
          # config_timezone: Europe/Moscow
