name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск ежедневно в полночь по UTC
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GHT }}
          filename: metrics.plugin.languages.details.svg

          # --- Конфигурация плагинов ---
          base: ""  # header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_aliases: javascript:JS typescript:TS
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4

          # Заготовки:
          # plugin_isocalendar: yes
          # plugin_lines: yes
          # plugin_traffic: yes

          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          committer_message: "chore: update GitHub metrics"

          # --- Дополнительные опции ---
          # config_timezone: Europe/Moscow
